# Server
server:
  port: 8085
  servlet:
    context-path: /project

spring:
  # MySQL
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.5:3306/study_test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  # Redis
  redis:
    host: 192.168.50.5
    port: 6379
  mvc:
    path match:
      matching-strategy: ant-path-matcher

# Spring Boot 整合 Mybatis
mybatis:
  # POJO 别名扫描包
  type-aliases-package: com.luobi.study.project
  # 加载 Mybatis 映射文件
  mapper-locations: classpath:mapper/*Mapper.xml
  # 开启 MyBatis 的 SQL 日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
